# Generated by Django 3.1.4 on 2020-12-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='ecuaciones')),
                ('ecuacion', models.TextField(blank=True, max_length=360)),
                ('solucion', models.TextField(blank=True, max_length=360)),
            ],
        ),
    ]
